# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.4.2]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - uses: bounceapp/render-action@0.6.0
      with:
        #heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        render-token: "rnd_NMlqnf82qZMN7GSewKNYFwi59qXF"
        service-id: "srv-cg895c1mbg53mc4n346g"
        #heroku_app_name: "app-zero-two"
        #heroku_email: "austin.sifuna@gmail.com"
    - run: node acceptance.js
